trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install Latest .NET 10 SDK'
  inputs:
    packageType: 'sdk'
    version: '10.x'

- task: DotNetCoreCLI@2
  displayName: '1. Build the project'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '2. Publish (Pack into Zip)'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true

- task: AzureWebApp@1
  displayName: '3. Deploy to Azure App Service'
  inputs:
    azureSubscription: 'Azure-Deploy-Connection'
    appType: 'webApp'
    appName: 'taskmanager-api'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'