namespace TaskManager.Application.Interfaces;

/// <summary>
/// Context DTO representing a candidate workforce member for task assignment.
/// </summary>
public record CandidateUserContext(
    Guid UserId,
    string FullName,
    string Username,
    string Role,
    decimal HourlyRate,
    IReadOnlyList<string> Skills
);

/// <summary>
/// Autonomous routing decision generated by Google Gemini.
/// </summary>
public record TaskRouterDecision(
    Guid? RecommendedAssigneeId,
    float ConfidenceScore,
    string ReasoningChain,
    string ModelVersion,
    int ExecutionTimeMs
);

/// <summary>
/// Intelligent Task Routing Engine powered by Google Gemini.
/// Evaluates task requirements against engineer skill matrices and team capacity.
/// </summary>
public interface IGeminiTaskRouterService
{
    Task<TaskRouterDecision> RouteTaskAsync(
        string title,
        string? description,
        string? requiredSkills,
        decimal estimatedHours,
        IReadOnlyList<CandidateUserContext> candidates,
        string? feedbackContext = null,
        CancellationToken cancellationToken = default);
}
